# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Spring AI - Google Gemini (using API Key)
# Make sure you have the 'spring-ai-google-genai-spring-boot-starter' dependency
spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

#spring.ai.google.genai.embedding.options.model=text-embedding-004

# Explicitly disable Vertex to avoid bean conflicts
spring.ai.vertex.ai.gemini.enabled=false